repos:
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # Choose the version you want
    hooks:
    -   id: pydocstyle
        additional_dependencies: ['toml']
        args: ['--convention=google']
        exclude: '^(tests/|docs/|setup.py)'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Choose the version you want
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: docstring-check
        name: docstring-check
        entry: python docstring-check.py --summary
        language: system
        types: [python]
        pass_filenames: false
