name: Docstring Check

on:
  push:
    branches: [ main, dev ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.py'
  workflow_dispatch:  # Allows manual triggering

jobs:
  docstring-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle flake8 flake8-docstrings
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run docstring checks
        run: |
          python docstring-check.py --summary

      - name: Generate detailed report
        if: ${{ always() }}
        run: |
          python docstring-check.py > docstring_report.txt

      - name: Upload docstring report as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: docstring-report
          path: docstring_report.txt
          retention-days: 7
